// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneClickShop.Domain.Data;

#nullable disable

namespace OneClickShop.Domain.Migrations
{
    [DbContext(typeof(OneClickSContext))]
    partial class OneClickSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneClickShop.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Teléfono inteligente de gama alta lanzado por Apple en octubre de 2020. Destaca por su pantalla Super Retina XDR de 6.7 pulgadas y el chip A14 Bionic",
                            Nombre = "Iphone 12 Pro Max",
                            Precio = 32000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = " portátil ligero y eficiente con pantalla Retina, teclado Magic Keyboard y procesadores Intel de 10ª generación, ideal para productividad y uso diario.",
                            Nombre = "MacBook Air 2020",
                            Precio = 40000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = " potente estación de trabajo todo en uno diseñada para profesionales, con hardware de alto rendimiento y una pantalla Retina 5K.",
                            Nombre = "iMac Pro 2019",
                            Precio = 300000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Laptop premium con pantalla Retina, procesador M1 Pro/Max y diseño compacto para creativos y profesionales.",
                            Nombre = "MacBook Pro 16",
                            Precio = 55000m,
                            Stock = 21
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Smartphone avanzado con pantalla Super Retina XDR, cámara triple y rendimiento optimizado con el chip A15 Bionic.",
                            Nombre = "iPhone 13 Pro",
                            Precio = 30000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Tablet versátil con pantalla Liquid Retina, chip M1 y compatibilidad con Apple Pencil y Magic Keyboard.",
                            Nombre = "iPad Air 2022",
                            Precio = 80000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Reloj inteligente con monitorización avanzada de salud, pantalla Always-On y resistencia al agua.",
                            Nombre = "Apple Watch Series 8",
                            Precio = 50000m,
                            Stock = 55
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
